sudo: false

language:
  - cpp

script:
  - mkdir build
  - cd build
  - cmake .. -DFTXUI_BUILD_TESTS=ON
  - cmake --build .
  - "${FTXUI_TEST_EXE}"

notifications:
  email: false

jobs:
  include:
    # Ubuntu
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - FTXUI_TEST_EXE="./tests --gtest_color=yes"

    # Ubuntu
    - os: linux
      dist: bionic
      compiler: clang
      env:
        - FTXUI_TEST_EXE="./tests --gtest_color=yes"

    # OS X
    - os: osx
      env:
        - FTXUI_TEST_EXE="./tests --gtest_color=yes"

    # Windows
    - os: windows
      env:
        - FTXUI_TEST_EXE="./Debug/tests.exe --gtest_color=yes"
